
/**
 * @file check_attribs.h
 *
 * Functions to free the attributes of node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: check_attribs.h.xsl 15657 2007-11-13 13:57:30Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_CHECK_ATTRIBS_H_
#define _SAC_CHECK_ATTRIBS_H_

#include "types.h"

extern char *CHKMattribString (char *attr, info * arg_info);
extern node *CHKMattribLink (node * attr, info * arg_info);

#endif /* _SAC_CHECK_ATTRIBS_H_ */
