
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYassign (node * arg_node, info * arg_info)
{
  node *result = TBmakeAssign (NULL, NULL);
  DBUG_ENTER ("COPYassign");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ASSIGN_EXPR (result) = COPYTRAV (ASSIGN_EXPR (arg_node), arg_info);
  ASSIGN_ID (result) = COPYTRAV (ASSIGN_ID (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbinop (node * arg_node, info * arg_info)
{
  node *result = TBmakeBinop (BO_unknown, NULL, NULL);
  DBUG_ENTER ("COPYbinop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BINOP_OP (result) = BINOP_OP (arg_node);
  /* Copy sons */
  BINOP_LEFT (result) = COPYTRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (result) = COPYTRAV (BINOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYblock
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Block node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYblock (node * arg_node, info * arg_info)
{
  node *result = TBmakeBlock (NULL);
  DBUG_ENTER ("COPYblock");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  BLOCK_STATEMENTS (result) =
    COPYTRAV (BLOCK_STATEMENTS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbool (node * arg_node, info * arg_info)
{
  node *result = TBmakeBool (FALSE);
  DBUG_ENTER ("COPYbool");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BOOL_VALUE (result) = BOOL_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYcast
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYcast (node * arg_node, info * arg_info)
{
  node *result = TBmakeCast (BT_unknown, NULL);
  DBUG_ENTER ("COPYcast");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  CAST_TYPE (result) = CAST_TYPE (arg_node);
  /* Copy sons */
  CAST_EXPR (result) = COPYTRAV (CAST_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdeclarations
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdeclarations (node * arg_node, info * arg_info)
{
  node *result = TBmakeDeclarations (NULL, NULL);
  DBUG_ENTER ("COPYdeclarations");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DECLARATIONS_DECLARATION (result) =
    COPYTRAV (DECLARATIONS_DECLARATION (arg_node), arg_info);
  DECLARATIONS_NEXT (result) =
    COPYTRAV (DECLARATIONS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdowhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdowhile (node * arg_node, info * arg_info)
{
  node *result = TBmakeDowhile (NULL, NULL);
  DBUG_ENTER ("COPYdowhile");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DOWHILE_EXPR (result) = COPYTRAV (DOWHILE_EXPR (arg_node), arg_info);
  DOWHILE_BLOCK (result) = COPYTRAV (DOWHILE_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYerror
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYerror (node * arg_node, info * arg_info)
{
  node *result = TBmakeError (NULL, PH_initial, NULL);
  DBUG_ENTER ("COPYerror");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ERROR_MESSAGE (result) = STRcpy (ERROR_MESSAGE (arg_node));
  ERROR_ANYPHASE (result) = ERROR_ANYPHASE (arg_node);
  /* Copy sons */
  ERROR_NEXT (result) = COPYTRAV (ERROR_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYexprs
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Exprs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYexprs (node * arg_node, info * arg_info)
{
  node *result = TBmakeExprs (NULL, NULL);
  DBUG_ENTER ("COPYexprs");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  EXPRS_EXPR (result) = COPYTRAV (EXPRS_EXPR (arg_node), arg_info);
  EXPRS_NEXT (result) = COPYTRAV (EXPRS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfloat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfloat (node * arg_node, info * arg_info)
{
  node *result = TBmakeFloat (0.0);
  DBUG_ENTER ("COPYfloat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FLOAT_VALUE (result) = FLOAT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfor
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfor (node * arg_node, info * arg_info)
{
  node *result = TBmakeFor (NULL, NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYfor");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FOR_COUNTERNAME (result) = STRcpy (FOR_COUNTERNAME (arg_node));
  /* Copy sons */
  FOR_STARTEXPR (result) = COPYTRAV (FOR_STARTEXPR (arg_node), arg_info);
  FOR_ENDEXPR (result) = COPYTRAV (FOR_ENDEXPR (arg_node), arg_info);
  FOR_STEPEXPR (result) = COPYTRAV (FOR_STEPEXPR (arg_node), arg_info);
  FOR_BLOCK (result) = COPYTRAV (FOR_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunbody
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunbody (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunbody (NULL, NULL);
  DBUG_ENTER ("COPYfunbody");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNBODY_LOCALFUNVARS (result) =
    COPYTRAV (FUNBODY_LOCALFUNVARS (arg_node), arg_info);
  FUNBODY_STATEMENTS (result) =
    COPYTRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfuncall
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfuncall (node * arg_node, info * arg_info)
{
  node *result = TBmakeFuncall (NULL, NULL);
  DBUG_ENTER ("COPYfuncall");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNCALL_NAME (result) = STRcpy (FUNCALL_NAME (arg_node));
  /* Copy sons */
  FUNCALL_PARAMS (result) = COPYTRAV (FUNCALL_PARAMS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundec (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundec (NULL);
  DBUG_ENTER ("COPYfundec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNDEC_FUNHEADER (result) =
    COPYTRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundef (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundef (FALSE, NULL, NULL, NULL);
  DBUG_ENTER ("COPYfundef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNDEF_EXPORT (result) = FUNDEF_EXPORT (arg_node);
  FUNDEF_SYMBOLTABLE (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), FUNDEF_SYMBOLTABLE (arg_node));
  /* Copy sons */
  FUNDEF_FUNHEADER (result) =
    COPYTRAV (FUNDEF_FUNHEADER (arg_node), arg_info);
  FUNDEF_FUNBODY (result) = COPYTRAV (FUNDEF_FUNBODY (arg_node), arg_info);
  FUNDEF_NEXT (result) = COPYTRAV (FUNDEF_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunheader
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunheader (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunheader (NULL, BT_unknown, NULL);
  DBUG_ENTER ("COPYfunheader");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNHEADER_NAME (result) = STRcpy (FUNHEADER_NAME (arg_node));
  FUNHEADER_RETTYPE (result) = FUNHEADER_RETTYPE (arg_node);
  /* Copy sons */
  FUNHEADER_PARAMS (result) =
    COPYTRAV (FUNHEADER_PARAMS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldec (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldec (BT_unknown, NULL);
  DBUG_ENTER ("COPYglobaldec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  GLOBALDEC_TYPE (result) = GLOBALDEC_TYPE (arg_node);
  GLOBALDEC_NAME (result) = STRcpy (GLOBALDEC_NAME (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldef (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldef (FALSE, BT_unknown, NULL, NULL);
  DBUG_ENTER ("COPYglobaldef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  GLOBALDEF_EXPORT (result) = GLOBALDEF_EXPORT (arg_node);
  GLOBALDEF_TYPE (result) = GLOBALDEF_TYPE (arg_node);
  GLOBALDEF_NAME (result) = STRcpy (GLOBALDEF_NAME (arg_node));
  /* Copy sons */
  GLOBALDEF_EXPR (result) = COPYTRAV (GLOBALDEF_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYid
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Id node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYid (node * arg_node, info * arg_info)
{
  node *result = TBmakeId (NULL);
  DBUG_ENTER ("COPYid");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ID_NAME (result) = STRcpy (ID_NAME (arg_node));
  ID_SYMBOLTABLE (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), ID_SYMBOLTABLE (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYifelse
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node IfElse node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYifelse (node * arg_node, info * arg_info)
{
  node *result = TBmakeIfelse (NULL, NULL, NULL);
  DBUG_ENTER ("COPYifelse");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  IFELSE_IFEXPR (result) = COPYTRAV (IFELSE_IFEXPR (arg_node), arg_info);
  IFELSE_IFBLOCK (result) = COPYTRAV (IFELSE_IFBLOCK (arg_node), arg_info);
  IFELSE_ELSEBLOCK (result) =
    COPYTRAV (IFELSE_ELSEBLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYint
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Int node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYint (node * arg_node, info * arg_info)
{
  node *result = TBmakeInt (0);
  DBUG_ENTER ("COPYint");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  INT_VALUE (result) = INT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmonop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmonop (node * arg_node, info * arg_info)
{
  node *result = TBmakeMonop (MO_unknown, NULL);
  DBUG_ENTER ("COPYmonop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MONOP_OP (result) = MONOP_OP (arg_node);
  /* Copy sons */
  MONOP_EXPR (result) = COPYTRAV (MONOP_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYparam
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYparam (node * arg_node, info * arg_info)
{
  node *result = TBmakeParam (BT_unknown, NULL, NULL);
  DBUG_ENTER ("COPYparam");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  PARAM_TYPE (result) = PARAM_TYPE (arg_node);
  PARAM_NAME (result) = STRcpy (PARAM_NAME (arg_node));
  /* Copy sons */
  PARAM_NEXT (result) = COPYTRAV (PARAM_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYprogram
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Program node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYprogram (node * arg_node, info * arg_info)
{
  node *result = TBmakeProgram (NULL);
  DBUG_ENTER ("COPYprogram");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  PROGRAM_SYMBOLTABLE (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), PROGRAM_SYMBOLTABLE (arg_node));
  /* Copy sons */
  PROGRAM_DECLARATIONS (result) =
    COPYTRAV (PROGRAM_DECLARATIONS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYreturn
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYreturn (node * arg_node, info * arg_info)
{
  node *result = TBmakeReturn (NULL);
  DBUG_ENTER ("COPYreturn");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  RETURN_RETVALUE (result) = COPYTRAV (RETURN_RETVALUE (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYstatements
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Statements node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYstatements (node * arg_node, info * arg_info)
{
  node *result = TBmakeStatements (NULL, NULL);
  DBUG_ENTER ("COPYstatements");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  STATEMENTS_STATEMENT (result) =
    COPYTRAV (STATEMENTS_STATEMENT (arg_node), arg_info);
  STATEMENTS_NEXT (result) = COPYTRAV (STATEMENTS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYsymboltable
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node SymbolTable node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYsymboltable (node * arg_node, info * arg_info)
{
  node *result = TBmakeSymboltable (NULL, NULL);
  DBUG_ENTER ("COPYsymboltable");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  SYMBOLTABLE_PARENT (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), SYMBOLTABLE_PARENT (arg_node));
  /* Copy sons */
  SYMBOLTABLE_ENTRIES (result) =
    COPYTRAV (SYMBOLTABLE_ENTRIES (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYsymboltableentry
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYsymboltableentry (node * arg_node, info * arg_info)
{
  node *result =
    TBmakeSymboltableentry (NULL, BT_unknown, FALSE, FALSE, FALSE, NULL);
  DBUG_ENTER ("COPYsymboltableentry");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  SYMBOLTABLEENTRY_NAME (result) = STRcpy (SYMBOLTABLEENTRY_NAME (arg_node));
  SYMBOLTABLEENTRY_TYPE (result) = SYMBOLTABLEENTRY_TYPE (arg_node);
  SYMBOLTABLEENTRY_PARAMS (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info),
		      SYMBOLTABLEENTRY_PARAMS (arg_node));
  SYMBOLTABLEENTRY_ISFUNCTION (result) =
    SYMBOLTABLEENTRY_ISFUNCTION (arg_node);
  SYMBOLTABLEENTRY_IMPORT (result) = SYMBOLTABLEENTRY_IMPORT (arg_node);
  SYMBOLTABLEENTRY_EXPORT (result) = SYMBOLTABLEENTRY_EXPORT (arg_node);
  /* Copy sons */
  SYMBOLTABLEENTRY_NEXT (result) =
    COPYTRAV (SYMBOLTABLEENTRY_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYternary
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Ternary node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYternary (node * arg_node, info * arg_info)
{
  node *result = TBmakeTernary (NULL, NULL, NULL);
  DBUG_ENTER ("COPYternary");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  TERNARY_PRED (result) = COPYTRAV (TERNARY_PRED (arg_node), arg_info);
  TERNARY_THEN (result) = COPYTRAV (TERNARY_THEN (arg_node), arg_info);
  TERNARY_ELSE (result) = COPYTRAV (TERNARY_ELSE (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvardec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvardec (node * arg_node, info * arg_info)
{
  node *result = TBmakeVardec (BT_unknown, NULL, NULL, NULL);
  DBUG_ENTER ("COPYvardec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VARDEC_TYPE (result) = VARDEC_TYPE (arg_node);
  VARDEC_NAME (result) = STRcpy (VARDEC_NAME (arg_node));
  /* Copy sons */
  VARDEC_EXPR (result) = COPYTRAV (VARDEC_EXPR (arg_node), arg_info);
  VARDEC_NEXT (result) = COPYTRAV (VARDEC_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYwhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYwhile (node * arg_node, info * arg_info)
{
  node *result = TBmakeWhile (NULL, NULL);
  DBUG_ENTER ("COPYwhile");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  WHILE_EXPR (result) = COPYTRAV (WHILE_EXPR (arg_node), arg_info);
  WHILE_BLOCK (result) = COPYTRAV (WHILE_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/**
 * @}
 */
