
/**
 * @file free_node.c
 *
 * Functions needed by free traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: free_node.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup free Free Tree Functions.
 *
 * Functions needed by free traversal.
 *
 * @{
 */


#include "free.h"
#include "free_node.h"
#include "free_attribs.h"
#include "free_info.h"
#include "tree_basic.h"
#include "traverse.h"
#include "str.h"
#include "memory.h"
#include "dbug.h"

#define FREETRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node
#define FREECOND( node, info)                                    \
  (INFO_FREE_FLAG( info) != arg_node)                            \
    ? FREETRAV( node, info)                                      \
    : (node)


/** <!--******************************************************************-->
 *
 * @fn FREEassign
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEassign (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEassign");
  DBUG_PRINT ("FREE", ("Processing node N_assign at " F_PTR, arg_node));
  ASSIGN_EXPR (arg_node) = FREETRAV (ASSIGN_EXPR (arg_node), arg_info);
  ASSIGN_ID (arg_node) = FREETRAV (ASSIGN_ID (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_assign = MEMfree (arg_node->sons.N_assign);
  arg_node->attribs.N_assign = MEMfree (arg_node->attribs.N_assign);
  DBUG_PRINT ("FREE", ("Processing node N_assign at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEbinop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEbinop (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEbinop");
  DBUG_PRINT ("FREE", ("Processing node N_binop at " F_PTR, arg_node));
  BINOP_LEFT (arg_node) = FREETRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (arg_node) = FREETRAV (BINOP_RIGHT (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_binop = MEMfree (arg_node->sons.N_binop);
  arg_node->attribs.N_binop = MEMfree (arg_node->attribs.N_binop);
  DBUG_PRINT ("FREE", ("Processing node N_binop at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEblock
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Block node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEblock (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEblock");
  DBUG_PRINT ("FREE", ("Processing node N_block at " F_PTR, arg_node));
  BLOCK_STATEMENTS (arg_node) =
    FREETRAV (BLOCK_STATEMENTS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_block = MEMfree (arg_node->sons.N_block);
  arg_node->attribs.N_block = MEMfree (arg_node->attribs.N_block);
  DBUG_PRINT ("FREE", ("Processing node N_block at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEbool
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEbool (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEbool");
  DBUG_PRINT ("FREE", ("Processing node N_bool at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_bool = MEMfree (arg_node->sons.N_bool);
  arg_node->attribs.N_bool = MEMfree (arg_node->attribs.N_bool);
  DBUG_PRINT ("FREE", ("Processing node N_bool at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEcast
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEcast (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEcast");
  DBUG_PRINT ("FREE", ("Processing node N_cast at " F_PTR, arg_node));
  CAST_EXPR (arg_node) = FREETRAV (CAST_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_cast = MEMfree (arg_node->sons.N_cast);
  arg_node->attribs.N_cast = MEMfree (arg_node->attribs.N_cast);
  DBUG_PRINT ("FREE", ("Processing node N_cast at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEdeclarations
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEdeclarations (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEdeclarations");
  DBUG_PRINT ("FREE", ("Processing node N_declarations at " F_PTR, arg_node));
  DECLARATIONS_NEXT (arg_node) =
    FREECOND (DECLARATIONS_NEXT (arg_node), arg_info);
  DECLARATIONS_DECLARATION (arg_node) =
    FREETRAV (DECLARATIONS_DECLARATION (arg_node), arg_info);
  result = DECLARATIONS_NEXT (arg_node);
  arg_node->sons.N_declarations = MEMfree (arg_node->sons.N_declarations);
  arg_node->attribs.N_declarations =
    MEMfree (arg_node->attribs.N_declarations);
  DBUG_PRINT ("FREE", ("Processing node N_declarations at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEdowhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEdowhile (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEdowhile");
  DBUG_PRINT ("FREE", ("Processing node N_dowhile at " F_PTR, arg_node));
  DOWHILE_EXPR (arg_node) = FREETRAV (DOWHILE_EXPR (arg_node), arg_info);
  DOWHILE_BLOCK (arg_node) = FREETRAV (DOWHILE_BLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_dowhile = MEMfree (arg_node->sons.N_dowhile);
  arg_node->attribs.N_dowhile = MEMfree (arg_node->attribs.N_dowhile);
  DBUG_PRINT ("FREE", ("Processing node N_dowhile at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEerror
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEerror (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEerror");
  DBUG_PRINT ("FREE", ("Processing node N_error at " F_PTR, arg_node));
  ERROR_NEXT (arg_node) = FREECOND (ERROR_NEXT (arg_node), arg_info);
  ERROR_MESSAGE (arg_node) =
    FREEattribString (ERROR_MESSAGE (arg_node), arg_node);
  result = ERROR_NEXT (arg_node);
  arg_node->sons.N_error = MEMfree (arg_node->sons.N_error);
  arg_node->attribs.N_error = MEMfree (arg_node->attribs.N_error);
  DBUG_PRINT ("FREE", ("Processing node N_error at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEexprs
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Exprs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEexprs (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEexprs");
  DBUG_PRINT ("FREE", ("Processing node N_exprs at " F_PTR, arg_node));
  EXPRS_NEXT (arg_node) = FREECOND (EXPRS_NEXT (arg_node), arg_info);
  EXPRS_EXPR (arg_node) = FREETRAV (EXPRS_EXPR (arg_node), arg_info);
  result = EXPRS_NEXT (arg_node);
  arg_node->sons.N_exprs = MEMfree (arg_node->sons.N_exprs);
  arg_node->attribs.N_exprs = MEMfree (arg_node->attribs.N_exprs);
  DBUG_PRINT ("FREE", ("Processing node N_exprs at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfloat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfloat (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfloat");
  DBUG_PRINT ("FREE", ("Processing node N_float at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_float = MEMfree (arg_node->sons.N_float);
  arg_node->attribs.N_float = MEMfree (arg_node->attribs.N_float);
  DBUG_PRINT ("FREE", ("Processing node N_float at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfor
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfor (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfor");
  DBUG_PRINT ("FREE", ("Processing node N_for at " F_PTR, arg_node));
  FOR_COUNTERNAME (arg_node) =
    FREEattribString (FOR_COUNTERNAME (arg_node), arg_node);
  FOR_STARTEXPR (arg_node) = FREETRAV (FOR_STARTEXPR (arg_node), arg_info);
  FOR_ENDEXPR (arg_node) = FREETRAV (FOR_ENDEXPR (arg_node), arg_info);
  FOR_STEPEXPR (arg_node) = FREETRAV (FOR_STEPEXPR (arg_node), arg_info);
  FOR_BLOCK (arg_node) = FREETRAV (FOR_BLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_for = MEMfree (arg_node->sons.N_for);
  arg_node->attribs.N_for = MEMfree (arg_node->attribs.N_for);
  DBUG_PRINT ("FREE", ("Processing node N_for at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunbody
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunbody (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunbody");
  DBUG_PRINT ("FREE", ("Processing node N_funbody at " F_PTR, arg_node));
  FUNBODY_LOCALFUNVARS (arg_node) =
    FREETRAV (FUNBODY_LOCALFUNVARS (arg_node), arg_info);
  FUNBODY_STATEMENTS (arg_node) =
    FREETRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_funbody = MEMfree (arg_node->sons.N_funbody);
  arg_node->attribs.N_funbody = MEMfree (arg_node->attribs.N_funbody);
  DBUG_PRINT ("FREE", ("Processing node N_funbody at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfuncall
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfuncall (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfuncall");
  DBUG_PRINT ("FREE", ("Processing node N_funcall at " F_PTR, arg_node));
  FUNCALL_NAME (arg_node) =
    FREEattribString (FUNCALL_NAME (arg_node), arg_node);
  FUNCALL_PARAMS (arg_node) = FREETRAV (FUNCALL_PARAMS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_funcall = MEMfree (arg_node->sons.N_funcall);
  arg_node->attribs.N_funcall = MEMfree (arg_node->attribs.N_funcall);
  DBUG_PRINT ("FREE", ("Processing node N_funcall at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfundec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfundec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfundec");
  DBUG_PRINT ("FREE", ("Processing node N_fundec at " F_PTR, arg_node));
  FUNDEC_FUNHEADER (arg_node) =
    FREETRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_fundec = MEMfree (arg_node->sons.N_fundec);
  arg_node->attribs.N_fundec = MEMfree (arg_node->attribs.N_fundec);
  DBUG_PRINT ("FREE", ("Processing node N_fundec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfundef
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfundef (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfundef");
  DBUG_PRINT ("FREE", ("Processing node N_fundef at " F_PTR, arg_node));
  FUNDEF_NEXT (arg_node) = FREECOND (FUNDEF_NEXT (arg_node), arg_info);
  FUNDEF_SYMBOLTABLE (arg_node) =
    FREEattribLink (FUNDEF_SYMBOLTABLE (arg_node), arg_node);
  FUNDEF_FUNHEADER (arg_node) =
    FREETRAV (FUNDEF_FUNHEADER (arg_node), arg_info);
  FUNDEF_FUNBODY (arg_node) = FREETRAV (FUNDEF_FUNBODY (arg_node), arg_info);
  result = FUNDEF_NEXT (arg_node);
  arg_node->sons.N_fundef = MEMfree (arg_node->sons.N_fundef);
  arg_node->attribs.N_fundef = MEMfree (arg_node->attribs.N_fundef);
  DBUG_PRINT ("FREE", ("Processing node N_fundef at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunheader
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunheader (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunheader");
  DBUG_PRINT ("FREE", ("Processing node N_funheader at " F_PTR, arg_node));
  FUNHEADER_NAME (arg_node) =
    FREEattribString (FUNHEADER_NAME (arg_node), arg_node);
  FUNHEADER_PARAMS (arg_node) =
    FREETRAV (FUNHEADER_PARAMS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_funheader = MEMfree (arg_node->sons.N_funheader);
  arg_node->attribs.N_funheader = MEMfree (arg_node->attribs.N_funheader);
  DBUG_PRINT ("FREE", ("Processing node N_funheader at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEglobaldec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEglobaldec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEglobaldec");
  DBUG_PRINT ("FREE", ("Processing node N_globaldec at " F_PTR, arg_node));
  GLOBALDEC_NAME (arg_node) =
    FREEattribString (GLOBALDEC_NAME (arg_node), arg_node);
  result = NULL;
  arg_node->sons.N_globaldec = MEMfree (arg_node->sons.N_globaldec);
  arg_node->attribs.N_globaldec = MEMfree (arg_node->attribs.N_globaldec);
  DBUG_PRINT ("FREE", ("Processing node N_globaldec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEglobaldef
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEglobaldef (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEglobaldef");
  DBUG_PRINT ("FREE", ("Processing node N_globaldef at " F_PTR, arg_node));
  GLOBALDEF_NAME (arg_node) =
    FREEattribString (GLOBALDEF_NAME (arg_node), arg_node);
  GLOBALDEF_EXPR (arg_node) = FREETRAV (GLOBALDEF_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_globaldef = MEMfree (arg_node->sons.N_globaldef);
  arg_node->attribs.N_globaldef = MEMfree (arg_node->attribs.N_globaldef);
  DBUG_PRINT ("FREE", ("Processing node N_globaldef at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEid
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Id node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEid (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEid");
  DBUG_PRINT ("FREE", ("Processing node N_id at " F_PTR, arg_node));
  ID_NAME (arg_node) = FREEattribString (ID_NAME (arg_node), arg_node);
  ID_SYMBOLTABLE (arg_node) =
    FREEattribLink (ID_SYMBOLTABLE (arg_node), arg_node);
  result = NULL;
  arg_node->sons.N_id = MEMfree (arg_node->sons.N_id);
  arg_node->attribs.N_id = MEMfree (arg_node->attribs.N_id);
  DBUG_PRINT ("FREE", ("Processing node N_id at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEifelse
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node IfElse node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEifelse (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEifelse");
  DBUG_PRINT ("FREE", ("Processing node N_ifelse at " F_PTR, arg_node));
  IFELSE_IFEXPR (arg_node) = FREETRAV (IFELSE_IFEXPR (arg_node), arg_info);
  IFELSE_IFBLOCK (arg_node) = FREETRAV (IFELSE_IFBLOCK (arg_node), arg_info);
  IFELSE_ELSEBLOCK (arg_node) =
    FREETRAV (IFELSE_ELSEBLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_ifelse = MEMfree (arg_node->sons.N_ifelse);
  arg_node->attribs.N_ifelse = MEMfree (arg_node->attribs.N_ifelse);
  DBUG_PRINT ("FREE", ("Processing node N_ifelse at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEint
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Int node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEint (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEint");
  DBUG_PRINT ("FREE", ("Processing node N_int at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_int = MEMfree (arg_node->sons.N_int);
  arg_node->attribs.N_int = MEMfree (arg_node->attribs.N_int);
  DBUG_PRINT ("FREE", ("Processing node N_int at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEmonop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEmonop (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEmonop");
  DBUG_PRINT ("FREE", ("Processing node N_monop at " F_PTR, arg_node));
  MONOP_EXPR (arg_node) = FREETRAV (MONOP_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_monop = MEMfree (arg_node->sons.N_monop);
  arg_node->attribs.N_monop = MEMfree (arg_node->attribs.N_monop);
  DBUG_PRINT ("FREE", ("Processing node N_monop at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEparam
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEparam (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEparam");
  DBUG_PRINT ("FREE", ("Processing node N_param at " F_PTR, arg_node));
  PARAM_NEXT (arg_node) = FREECOND (PARAM_NEXT (arg_node), arg_info);
  PARAM_NAME (arg_node) = FREEattribString (PARAM_NAME (arg_node), arg_node);
  result = PARAM_NEXT (arg_node);
  arg_node->sons.N_param = MEMfree (arg_node->sons.N_param);
  arg_node->attribs.N_param = MEMfree (arg_node->attribs.N_param);
  DBUG_PRINT ("FREE", ("Processing node N_param at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEprogram
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Program node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEprogram (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEprogram");
  DBUG_PRINT ("FREE", ("Processing node N_program at " F_PTR, arg_node));
  PROGRAM_SYMBOLTABLE (arg_node) =
    FREEattribLink (PROGRAM_SYMBOLTABLE (arg_node), arg_node);
  PROGRAM_DECLARATIONS (arg_node) =
    FREETRAV (PROGRAM_DECLARATIONS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_program = MEMfree (arg_node->sons.N_program);
  arg_node->attribs.N_program = MEMfree (arg_node->attribs.N_program);
  DBUG_PRINT ("FREE", ("Processing node N_program at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEreturn
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEreturn (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEreturn");
  DBUG_PRINT ("FREE", ("Processing node N_return at " F_PTR, arg_node));
  RETURN_RETVALUE (arg_node) =
    FREETRAV (RETURN_RETVALUE (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_return = MEMfree (arg_node->sons.N_return);
  arg_node->attribs.N_return = MEMfree (arg_node->attribs.N_return);
  DBUG_PRINT ("FREE", ("Processing node N_return at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEstatements
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Statements node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEstatements (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEstatements");
  DBUG_PRINT ("FREE", ("Processing node N_statements at " F_PTR, arg_node));
  STATEMENTS_NEXT (arg_node) =
    FREECOND (STATEMENTS_NEXT (arg_node), arg_info);
  STATEMENTS_STATEMENT (arg_node) =
    FREETRAV (STATEMENTS_STATEMENT (arg_node), arg_info);
  result = STATEMENTS_NEXT (arg_node);
  arg_node->sons.N_statements = MEMfree (arg_node->sons.N_statements);
  arg_node->attribs.N_statements = MEMfree (arg_node->attribs.N_statements);
  DBUG_PRINT ("FREE", ("Processing node N_statements at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEsymboltable
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node SymbolTable node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEsymboltable (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEsymboltable");
  DBUG_PRINT ("FREE", ("Processing node N_symboltable at " F_PTR, arg_node));
  SYMBOLTABLE_PARENT (arg_node) =
    FREEattribLink (SYMBOLTABLE_PARENT (arg_node), arg_node);
  SYMBOLTABLE_ENTRIES (arg_node) =
    FREETRAV (SYMBOLTABLE_ENTRIES (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_symboltable = MEMfree (arg_node->sons.N_symboltable);
  arg_node->attribs.N_symboltable = MEMfree (arg_node->attribs.N_symboltable);
  DBUG_PRINT ("FREE", ("Processing node N_symboltable at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEsymboltableentry
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEsymboltableentry (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEsymboltableentry");
  DBUG_PRINT ("FREE",
	      ("Processing node N_symboltableentry at " F_PTR, arg_node));
  SYMBOLTABLEENTRY_NEXT (arg_node) =
    FREECOND (SYMBOLTABLEENTRY_NEXT (arg_node), arg_info);
  SYMBOLTABLEENTRY_NAME (arg_node) =
    FREEattribString (SYMBOLTABLEENTRY_NAME (arg_node), arg_node);
  SYMBOLTABLEENTRY_PARAMS (arg_node) =
    FREEattribLink (SYMBOLTABLEENTRY_PARAMS (arg_node), arg_node);
  result = SYMBOLTABLEENTRY_NEXT (arg_node);
  arg_node->sons.N_symboltableentry =
    MEMfree (arg_node->sons.N_symboltableentry);
  arg_node->attribs.N_symboltableentry =
    MEMfree (arg_node->attribs.N_symboltableentry);
  DBUG_PRINT ("FREE",
	      ("Processing node N_symboltableentry at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEternary
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Ternary node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEternary (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEternary");
  DBUG_PRINT ("FREE", ("Processing node N_ternary at " F_PTR, arg_node));
  TERNARY_PRED (arg_node) = FREETRAV (TERNARY_PRED (arg_node), arg_info);
  TERNARY_THEN (arg_node) = FREETRAV (TERNARY_THEN (arg_node), arg_info);
  TERNARY_ELSE (arg_node) = FREETRAV (TERNARY_ELSE (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_ternary = MEMfree (arg_node->sons.N_ternary);
  arg_node->attribs.N_ternary = MEMfree (arg_node->attribs.N_ternary);
  DBUG_PRINT ("FREE", ("Processing node N_ternary at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEvardec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEvardec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEvardec");
  DBUG_PRINT ("FREE", ("Processing node N_vardec at " F_PTR, arg_node));
  VARDEC_NEXT (arg_node) = FREECOND (VARDEC_NEXT (arg_node), arg_info);
  VARDEC_NAME (arg_node) =
    FREEattribString (VARDEC_NAME (arg_node), arg_node);
  VARDEC_EXPR (arg_node) = FREETRAV (VARDEC_EXPR (arg_node), arg_info);
  result = VARDEC_NEXT (arg_node);
  arg_node->sons.N_vardec = MEMfree (arg_node->sons.N_vardec);
  arg_node->attribs.N_vardec = MEMfree (arg_node->attribs.N_vardec);
  DBUG_PRINT ("FREE", ("Processing node N_vardec at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEwhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEwhile (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEwhile");
  DBUG_PRINT ("FREE", ("Processing node N_while at " F_PTR, arg_node));
  WHILE_EXPR (arg_node) = FREETRAV (WHILE_EXPR (arg_node), arg_info);
  WHILE_BLOCK (arg_node) = FREETRAV (WHILE_BLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_while = MEMfree (arg_node->sons.N_while);
  arg_node->attribs.N_while = MEMfree (arg_node->attribs.N_while);
  DBUG_PRINT ("FREE", ("Processing node N_while at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/**
 * @}
 */
