
/**
 * @file traverse_tables.c
 *
 * This file defines the function tables for traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_tables.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "traverse_tables.h"
#include "traverse_helper.h"
#include "print.h"
#include "copy_node.h"
#include "free_node.h"
#include "check.h"
#include "enforce_return.h"
#include "symbol_table.h"
#include "symbol_table_check.h"
#include "typecheck.h"
#include "global_init.h"
#include "for_to_while.h"
#include "boolean_cast.h"
#include "arithmetic_optimisation.h"
#include "rename_identifiers.h"
#include "gen_byte_code.h"


travtables_t travtables = {
  /* TR_undefined */
  {&TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror}

  /* TR_prt */
  , {&TRAVerror, &PRTprogram, &PRTdeclarations, &PRTfundec, &PRTfundef,
     &PRTfunheader, &PRTglobaldec, &PRTglobaldef, &PRTparam, &PRTblock,
     &PRTfunbody, &PRTvardec, &PRTstatements, &PRTassign, &PRTifelse,
     &PRTwhile, &PRTdowhile, &PRTfor, &PRTreturn, &PRTexprs, &PRTbinop,
     &PRTmonop, &PRTcast, &PRTfuncall, &PRTid, &PRTint, &PRTfloat,
     &PRTternary, &PRTbool, &PRTsymboltable, &PRTsymboltableentry, &PRTerror}

  /* TR_copy */
  , {&TRAVerror, &COPYprogram, &COPYdeclarations, &COPYfundec, &COPYfundef,
     &COPYfunheader, &COPYglobaldec, &COPYglobaldef, &COPYparam, &COPYblock,
     &COPYfunbody, &COPYvardec, &COPYstatements, &COPYassign, &COPYifelse,
     &COPYwhile, &COPYdowhile, &COPYfor, &COPYreturn, &COPYexprs, &COPYbinop,
     &COPYmonop, &COPYcast, &COPYfuncall, &COPYid, &COPYint, &COPYfloat,
     &COPYternary, &COPYbool, &COPYsymboltable, &COPYsymboltableentry,
     &COPYerror}

  /* TR_free */
  , {&TRAVerror, &FREEprogram, &FREEdeclarations, &FREEfundec, &FREEfundef,
     &FREEfunheader, &FREEglobaldec, &FREEglobaldef, &FREEparam, &FREEblock,
     &FREEfunbody, &FREEvardec, &FREEstatements, &FREEassign, &FREEifelse,
     &FREEwhile, &FREEdowhile, &FREEfor, &FREEreturn, &FREEexprs, &FREEbinop,
     &FREEmonop, &FREEcast, &FREEfuncall, &FREEid, &FREEint, &FREEfloat,
     &FREEternary, &FREEbool, &FREEsymboltable, &FREEsymboltableentry,
     &FREEerror}

  /* TR_chk */
  , {&TRAVerror, &CHKprogram, &CHKdeclarations, &CHKfundec, &CHKfundef,
     &CHKfunheader, &CHKglobaldec, &CHKglobaldef, &CHKparam, &CHKblock,
     &CHKfunbody, &CHKvardec, &CHKstatements, &CHKassign, &CHKifelse,
     &CHKwhile, &CHKdowhile, &CHKfor, &CHKreturn, &CHKexprs, &CHKbinop,
     &CHKmonop, &CHKcast, &CHKfuncall, &CHKid, &CHKint, &CHKfloat,
     &CHKternary, &CHKbool, &CHKsymboltable, &CHKsymboltableentry, &CHKerror}

  /* TR_er */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &ERfundef, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons}

  /* TR_st */
  , {&TRAVerror, &STprogram, &STdeclarations, &STfundec, &STfundef, &TRAVsons,
     &STglobaldec, &STglobaldef, &STparam, &TRAVsons, &TRAVsons, &STvardec,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &STid,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_stc */
  , {&TRAVerror, &STCprogram, &TRAVsons, &TRAVsons, &STCfundef, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &STCfuncall,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons}

  /* TR_tc */
  , {&TRAVerror, &TCprogram, &TRAVsons, &TRAVsons, &TCfundef, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TCvardec,
     &TRAVsons, &TCassign, &TCifelse, &TCwhile, &TCdowhile, &TCfor, &TCreturn,
     &TRAVsons, &TCbinop, &TCmonop, &TCcast, &TCfuncall, &TCid, &TCint,
     &TCfloat, &TCternary, &TCbool, &TRAVsons, &TRAVsons, &TRAVsons}

  /* TR_gi */
  , {&TRAVerror, &GIprogram, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &GIglobaldef, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons}

  /* TR_ftw */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &FTWstatements, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &FTWfor,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons}

  /* TR_bc */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &BCbinop, &TRAVsons, &BCcast, &TRAVsons, &BCid,
     &BCint, &BCfloat, &TRAVsons, &BCbool, &TRAVsons, &TRAVsons, &TRAVsons}

  /* TR_ao */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &AObinop, &AOmonop, &AOcast, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &AOternary, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_ri */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &RIfundef, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &RIvardec,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &RIfor, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &RIfuncall, &RIid, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

  /* TR_gbc */
  , {&TRAVerror, &GBCprogram, &TRAVsons, &TRAVsons, &GBCfundef, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &GBCblock, &GBCfunbody, &GBCvardec,
     &GBCstatements, &GBCassign, &GBCifelse, &GBCwhile, &GBCdowhile,
     &TRAVsons, &GBCreturn, &TRAVsons, &GBCbinop, &GBCmonop, &GBCcast,
     &GBCfuncall, &GBCid, &GBCint, &GBCfloat, &GBCternary, &GBCbool,
     &TRAVsons, &GBCsymboltableentry, &TRAVsons}
};

preposttable_t pretable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL
};

preposttable_t posttable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL
};

const char *travnames[15] = {
  "unknown", "prt", "copy", "free", "chk", "er", "st", "stc", "tc", "gi",
    "ftw", "bc", "ao", "ri", "gbc"
};
