
/**
 * @file traverse_helper.c
 *
 * Defines the helper function needed by the traversal system
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_helper.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */


#include "traverse_helper.h"
#include "dbug.h"
#include "tree_basic.h"
#include "traverse.h"

#define TRAV( son, info)    if (son != NULL) { son = TRAVdo( son, info); }

node *
TRAVnone (node * arg_node, info * arg_info)
{
  return (arg_node);
}

node *
TRAVerror (node * arg_node, info * arg_info)
{
  DBUG_ASSERT ((FALSE), "Illegal node type found.");

  return (arg_node);
}

node *
TRAVsons (node * arg_node, info * arg_info)
{
  switch (NODE_TYPE (arg_node))
    {
    case N_program:
      TRAV (PROGRAM_DECLARATIONS (arg_node), arg_info);
      break;
    case N_declarations:
      TRAV (DECLARATIONS_DECLARATION (arg_node), arg_info);
      TRAV (DECLARATIONS_NEXT (arg_node), arg_info);
      break;
    case N_fundec:
      TRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
      break;
    case N_fundef:
      TRAV (FUNDEF_FUNHEADER (arg_node), arg_info);
      TRAV (FUNDEF_FUNBODY (arg_node), arg_info);
      TRAV (FUNDEF_NEXT (arg_node), arg_info);
      break;
    case N_funheader:
      TRAV (FUNHEADER_PARAMS (arg_node), arg_info);
      break;
    case N_globaldec:
      break;
    case N_globaldef:
      TRAV (GLOBALDEF_EXPR (arg_node), arg_info);
      break;
    case N_param:
      TRAV (PARAM_NEXT (arg_node), arg_info);
      break;
    case N_block:
      TRAV (BLOCK_STATEMENTS (arg_node), arg_info);
      break;
    case N_funbody:
      TRAV (FUNBODY_LOCALFUNVARS (arg_node), arg_info);
      TRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
      break;
    case N_vardec:
      TRAV (VARDEC_EXPR (arg_node), arg_info);
      TRAV (VARDEC_NEXT (arg_node), arg_info);
      break;
    case N_statements:
      TRAV (STATEMENTS_STATEMENT (arg_node), arg_info);
      TRAV (STATEMENTS_NEXT (arg_node), arg_info);
      break;
    case N_assign:
      TRAV (ASSIGN_EXPR (arg_node), arg_info);
      TRAV (ASSIGN_ID (arg_node), arg_info);
      break;
    case N_ifelse:
      TRAV (IFELSE_IFEXPR (arg_node), arg_info);
      TRAV (IFELSE_IFBLOCK (arg_node), arg_info);
      TRAV (IFELSE_ELSEBLOCK (arg_node), arg_info);
      break;
    case N_while:
      TRAV (WHILE_EXPR (arg_node), arg_info);
      TRAV (WHILE_BLOCK (arg_node), arg_info);
      break;
    case N_dowhile:
      TRAV (DOWHILE_EXPR (arg_node), arg_info);
      TRAV (DOWHILE_BLOCK (arg_node), arg_info);
      break;
    case N_for:
      TRAV (FOR_STARTEXPR (arg_node), arg_info);
      TRAV (FOR_ENDEXPR (arg_node), arg_info);
      TRAV (FOR_STEPEXPR (arg_node), arg_info);
      TRAV (FOR_BLOCK (arg_node), arg_info);
      break;
    case N_return:
      TRAV (RETURN_RETVALUE (arg_node), arg_info);
      break;
    case N_exprs:
      TRAV (EXPRS_EXPR (arg_node), arg_info);
      TRAV (EXPRS_NEXT (arg_node), arg_info);
      break;
    case N_binop:
      TRAV (BINOP_LEFT (arg_node), arg_info);
      TRAV (BINOP_RIGHT (arg_node), arg_info);
      break;
    case N_monop:
      TRAV (MONOP_EXPR (arg_node), arg_info);
      break;
    case N_cast:
      TRAV (CAST_EXPR (arg_node), arg_info);
      break;
    case N_funcall:
      TRAV (FUNCALL_PARAMS (arg_node), arg_info);
      break;
    case N_id:
      break;
    case N_int:
      break;
    case N_float:
      break;
    case N_ternary:
      TRAV (TERNARY_PRED (arg_node), arg_info);
      TRAV (TERNARY_THEN (arg_node), arg_info);
      TRAV (TERNARY_ELSE (arg_node), arg_info);
      break;
    case N_bool:
      break;
    case N_symboltable:
      TRAV (SYMBOLTABLE_ENTRIES (arg_node), arg_info);
      break;
    case N_symboltableentry:
      TRAV (SYMBOLTABLEENTRY_NEXT (arg_node), arg_info);
      break;
    case N_error:
      TRAV (ERROR_NEXT (arg_node), arg_info);
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  return (arg_node);
}

int
TRAVnumSons (node * node)
{
  int result = 0;

  DBUG_ENTER ("TRAVnumSons");

  switch (NODE_TYPE (node))
    {
    case N_program:
      result = 1;
      break;
    case N_declarations:
      result = 2;
      break;
    case N_fundec:
      result = 1;
      break;
    case N_fundef:
      result = 3;
      break;
    case N_funheader:
      result = 1;
      break;
    case N_globaldec:
      result = 0;
      break;
    case N_globaldef:
      result = 1;
      break;
    case N_param:
      result = 1;
      break;
    case N_block:
      result = 1;
      break;
    case N_funbody:
      result = 2;
      break;
    case N_vardec:
      result = 2;
      break;
    case N_statements:
      result = 2;
      break;
    case N_assign:
      result = 2;
      break;
    case N_ifelse:
      result = 3;
      break;
    case N_while:
      result = 2;
      break;
    case N_dowhile:
      result = 2;
      break;
    case N_for:
      result = 4;
      break;
    case N_return:
      result = 1;
      break;
    case N_exprs:
      result = 2;
      break;
    case N_binop:
      result = 2;
      break;
    case N_monop:
      result = 1;
      break;
    case N_cast:
      result = 1;
      break;
    case N_funcall:
      result = 1;
      break;
    case N_id:
      result = 0;
      break;
    case N_int:
      result = 0;
      break;
    case N_float:
      result = 0;
      break;
    case N_ternary:
      result = 3;
      break;
    case N_bool:
      result = 0;
      break;
    case N_symboltable:
      result = 1;
      break;
    case N_symboltableentry:
      result = 1;
      break;
    case N_error:
      result = 1;
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}

node *
TRAVgetSon (int no, node * parent)
{
  node *result = NULL;

  DBUG_ENTER ("TRAVgetSon");

  switch (NODE_TYPE (parent))
    {
    case N_program:
      switch (no)
	{
	case 0:
	  result = PROGRAM_DECLARATIONS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_declarations:
      switch (no)
	{
	case 0:
	  result = DECLARATIONS_DECLARATION (parent);
	  break;
	case 1:
	  result = DECLARATIONS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_fundec:
      switch (no)
	{
	case 0:
	  result = FUNDEC_FUNHEADER (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_fundef:
      switch (no)
	{
	case 0:
	  result = FUNDEF_FUNHEADER (parent);
	  break;
	case 1:
	  result = FUNDEF_FUNBODY (parent);
	  break;
	case 2:
	  result = FUNDEF_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funheader:
      switch (no)
	{
	case 0:
	  result = FUNHEADER_PARAMS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_globaldec:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_globaldef:
      switch (no)
	{
	case 0:
	  result = GLOBALDEF_EXPR (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_param:
      switch (no)
	{
	case 0:
	  result = PARAM_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_block:
      switch (no)
	{
	case 0:
	  result = BLOCK_STATEMENTS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funbody:
      switch (no)
	{
	case 0:
	  result = FUNBODY_LOCALFUNVARS (parent);
	  break;
	case 1:
	  result = FUNBODY_STATEMENTS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_vardec:
      switch (no)
	{
	case 0:
	  result = VARDEC_EXPR (parent);
	  break;
	case 1:
	  result = VARDEC_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_statements:
      switch (no)
	{
	case 0:
	  result = STATEMENTS_STATEMENT (parent);
	  break;
	case 1:
	  result = STATEMENTS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_assign:
      switch (no)
	{
	case 0:
	  result = ASSIGN_EXPR (parent);
	  break;
	case 1:
	  result = ASSIGN_ID (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_ifelse:
      switch (no)
	{
	case 0:
	  result = IFELSE_IFEXPR (parent);
	  break;
	case 1:
	  result = IFELSE_IFBLOCK (parent);
	  break;
	case 2:
	  result = IFELSE_ELSEBLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_while:
      switch (no)
	{
	case 0:
	  result = WHILE_EXPR (parent);
	  break;
	case 1:
	  result = WHILE_BLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_dowhile:
      switch (no)
	{
	case 0:
	  result = DOWHILE_EXPR (parent);
	  break;
	case 1:
	  result = DOWHILE_BLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_for:
      switch (no)
	{
	case 0:
	  result = FOR_STARTEXPR (parent);
	  break;
	case 1:
	  result = FOR_ENDEXPR (parent);
	  break;
	case 2:
	  result = FOR_STEPEXPR (parent);
	  break;
	case 3:
	  result = FOR_BLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_return:
      switch (no)
	{
	case 0:
	  result = RETURN_RETVALUE (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_exprs:
      switch (no)
	{
	case 0:
	  result = EXPRS_EXPR (parent);
	  break;
	case 1:
	  result = EXPRS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_binop:
      switch (no)
	{
	case 0:
	  result = BINOP_LEFT (parent);
	  break;
	case 1:
	  result = BINOP_RIGHT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_monop:
      switch (no)
	{
	case 0:
	  result = MONOP_EXPR (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_cast:
      switch (no)
	{
	case 0:
	  result = CAST_EXPR (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funcall:
      switch (no)
	{
	case 0:
	  result = FUNCALL_PARAMS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_id:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_int:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_float:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_ternary:
      switch (no)
	{
	case 0:
	  result = TERNARY_PRED (parent);
	  break;
	case 1:
	  result = TERNARY_THEN (parent);
	  break;
	case 2:
	  result = TERNARY_ELSE (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_bool:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_symboltable:
      switch (no)
	{
	case 0:
	  result = SYMBOLTABLE_ENTRIES (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_symboltableentry:
      switch (no)
	{
	case 0:
	  result = SYMBOLTABLEENTRY_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_error:
      switch (no)
	{
	case 0:
	  result = ERROR_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}
