
/**
 * @file types_trav.h
 *
 * This file defines the trav_t phase enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_trav.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_TRAV_H_
#define _SAC_TYPES_TRAV_H_

typedef enum
{ TR_undefined = 0, TR_prt = 1, TR_copy = 2, TR_free = 3, TR_chk = 4, TR_er =
    5, TR_st = 6, TR_stc = 7, TR_tc = 8, TR_gi = 9, TR_ftw = 10, TR_bc =
    11, TR_ao = 12, TR_ri = 13, TR_gbc = 14 } trav_t;
#endif /* _SAC_TYPES_TRAV_H_ */
