
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 31
typedef enum
{ N_undefined = 0, N_program = 1, N_declarations = 2, N_fundec = 3, N_fundef =
    4, N_funheader = 5, N_globaldec = 6, N_globaldef = 7, N_param =
    8, N_block = 9, N_funbody = 10, N_vardec = 11, N_statements =
    12, N_assign = 13, N_ifelse = 14, N_while = 15, N_dowhile = 16, N_for =
    17, N_return = 18, N_exprs = 19, N_binop = 20, N_monop = 21, N_cast =
    22, N_funcall = 23, N_id = 24, N_int = 25, N_float = 26, N_ternary =
    27, N_bool = 28, N_symboltable = 29, N_symboltableentry = 30, N_error =
    31 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
