#ifndef GLOBALtype
#define GLOBALtype( type)
#endif

#ifndef GLOBALname
#define GLOBALname( name)
#endif

#ifndef GLOBALinit
#define GLOBALinit( init)
#endif


#define GLOBAL( type, name, init) GLOBALtype(type) GLOBALname(name) GLOBALinit(init)


/*
 * CiviCC specific global variables
 */

#if 0
GLOBAL( type, name, init)
#endif

#undef GLOBALtype
#undef GLOBALname
#undef GLOBALinit
#undef GLOBAL


