# ---------------------------------------------------------------------------
#
# SAC Compiler Construction Framework
#
# ---------------------------------------------------------------------------
#
# SAC COPYRIGHT NOTICE, LICENSE, AND DISCLAIMER
#
# (c) Copyright 1994 - 2011 by
#
#   SAC Development Team
#   SAC Research Foundation
#
#   http://www.sac-home.org
#   email:info@sac-home.org
#
#   All rights reserved
#
# ---------------------------------------------------------------------------
#
# The SAC compiler construction framework, all accompanying
# software and documentation (in the following named this software)
# is developed by the SAC Development Team (in the following named
# the developer) which reserves all rights on this software.
#
# Permission to use this software is hereby granted free of charge
# exclusively for the duration and purpose of the course
#   "Compilerbouw"
# of the MSc programme Grid Computing at the University of Amsterdam.
# Redistribution of the software or any parts thereof as well as any
# alteration  of the software or any parts thereof other than those
# required to use the compiler construction framework for the purpose
# of the above mentioned course are not permitted.
#
# The developer disclaims all warranties with regard to this software,
# including all implied warranties of merchantability and fitness.  In no
# event shall the developer be liable for any special, indirect or
# consequential damages or any damages whatsoever resulting from loss of
# use, data, or profits, whether in an action of contract, negligence, or
# other tortuous action, arising out of or in connection with the use or
# performance of this software. The entire risk as to the quality and
# performance of this software is with you. Should this software prove
# defective, you assume the cost of all servicing, repair, or correction.
#
# ---------------------------------------------------------------------------
#



###############################################################################
#
# Collection of source directories
#


src = global scanparse print codegen analysis codetrans optimisations framework

TEST_DIRS := basic nested_funs # arrays preprocess
TEST_CFLAGS := ""
TEST_RUN_FUNCTIONAL := 0
TEST_CIVAS := bin/civas
TEST_CIVVM := bin/civvm
TEST_CIVCC := bin/civicc



###############################################################################
#
# Collection of object files
#
#  Note that the variable names must coincide with the directory names above.


framework   = memory.o str.o ctinfo.o main_args.o dbug.o globals.o \
              free_attribs.o free.o copy.o traverse.o scanparse.o main.o \
              phase.o phase_drivers.o phase_info.o phase_options.o \
              check_lib.o node_basic.o free_node.o copy_node.o \
              traverse_tables.o traverse_helper.o check.o \
              check_node.o check_attribs.o lookup_table.o map.o

global      = options.o usage.o myglobals.o general_functions.o

scanparse   = civic.tab.o civic.lex.o

analysis    = symbol_table.o symbol_table_check.o typecheck.o rename_identifiers.o

codetrans   = global_init.o for_to_while.o boolean_cast.o enforce_return.o

print       = print.o

codegen     = gen_byte_code.o table.o


optimisations = arithmetic_optimisation.o
